engine: "postgres"

docker:
  image: "postgres:17-alpine"
  container_name: "restore-assert-pg"
  memory_limit: "1GB"
  cpu_limit: "1.0"
  wait_timeout: "60s"
  auto_remove: true

database:
  db_name: "restore_test"
  user: "postgres"
  password: "password"
  extensions:
    - "uuid-ossp"
    - "pgcrypto"
  roles:
    - "web_app"
    - "bi_tool"
    - "migration_service"
  settings:
    fsync: "off" # Ускоряет восстановление
    shared_buffers: "256MB"
    work_mem: "64MB"
    
# Параметры восстановления (Restore)
restore:
  # Not always required
  #format: "custom"  
  parallel_jobs: 4
  analyze: true
  on_error_stop: false
  single_transaction: false
  no_owner: true
  no_privileges: true